name: Documentation Improvement
description: Suggest improvements to project or plugin documentation.
labels: ["documentation"]
body:
  - type: dropdown
    id: documentation-target
    attributes:
      label: Documentation Target
      description: Which document needs improvement?
      options:
        - "Project README (README.md)"
        - "Contributing Guide (CONTRIBUTING.md)"
        - "claude-logger README"
        - "hello-plugin README"
        - "technical-writing README"
        - "git-workflow README"
        - "SKILL.md (specific skill documentation)"
        - "Agent documentation"
        - Other
    validations:
      required: true

  - type: dropdown
    id: improvement-type
    attributes:
      label: Type of Improvement
      description: What kind of improvement is needed?
      options:
        - Typo or grammar fix
        - Missing information
        - Clarification of existing content
        - Add examples or code snippets
        - Restructure or reorganize
        - Translation
        - Other
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: Describe the current state of the documentation, including what is incorrect or missing.
      placeholder: The current documentation says... / The documentation is missing...
    validations:
      required: true

  - type: textarea
    id: proposed-change
    attributes:
      label: Proposed Change
      description: Describe what the documentation should say or how it should be changed.
      placeholder: The documentation should be updated to...
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the documentation improvement.
    validations:
      required: false
