name: Feature Request
description: Suggest a new feature or enhancement for an existing plugin.
labels: ["enhancement"]
body:
  - type: dropdown
    id: target-plugin
    attributes:
      label: Target Plugin
      description: Which plugin should this feature be added to?
      options:
        - claude-logger
        - hello-plugin
        - technical-writing
        - git-workflow
        - github-workflow
        - project-analyzer
        - Marketplace (core)
        - New plugin (use the "New Plugin Proposal" template instead)
    validations:
      required: true

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What type of component does this feature involve?
      options:
        - New Skill
        - New Agent
        - New Hook
        - Enhancement to existing Skill
        - Enhancement to existing Agent
        - Enhancement to existing Hook
        - Other
    validations:
      required: false

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Describe the use case.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Describe alternatives...
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request.
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I am willing to submit a pull request for this feature.
          required: false
